// <auto-generated />
using Edvantix.System.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.System.Infrastructure.Migrations
{
    [DbContext(typeof(SystemContext))]
    partial class SystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.System.Domain.AggregatesModel.LimitAggregate.Limit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_limit");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_limit_subscription_id");

                    b.HasIndex("SubscriptionId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_limit_subscription_id_type");

                    b.ToTable("limit", (string)null);
                });

            modelBuilder.Entity("Edvantix.System.Domain.AggregatesModel.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_subscription");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_subscription_currency_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_subscription_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_subscription_type");

                    b.ToTable("subscription", (string)null);
                });

            modelBuilder.Entity("Edvantix.System.Domain.AggregatesModel.LimitAggregate.Limit", b =>
                {
                    b.HasOne("Edvantix.System.Domain.AggregatesModel.SubscriptionAggregate.Subscription", "Subscription")
                        .WithMany("Limits")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_limit_subscription_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Edvantix.System.Domain.AggregatesModel.SubscriptionAggregate.Subscription", b =>
                {
                    b.Navigation("Limits");
                });
#pragma warning restore 612, 618
        }
    }
}
