// Synthetic but realistic Russian student data for the Edvantix school
const STUDENTS = [
  { id: 1, name: 'Анна Сергеева',     email: 'a.sergeeva@gmail.com',     phone: '+7 (916) 312-44-09',
    group: 'Дизайн-3 · поток апр.',   courses: ['UX/UI дизайн', 'Figma для команд'], status: 'active',
    progress: 78, payment: 'paid', paidUntil: '12 июл.', enrolled: '03 фев. 2026', lastActive: '5 мин назад', avatarSeed: 'pink' },
  { id: 2, name: 'Дмитрий Соколов',   email: 'd.sokolov@yandex.ru',      phone: '+7 (903) 558-11-72',
    group: 'Python-junior · б.',      courses: ['Python для детей'], status: 'active',
    progress: 42, payment: 'overdue', paidUntil: '04 мая', enrolled: '18 янв. 2026', lastActive: '2 часа назад', avatarSeed: 'blue' },
  { id: 3, name: 'Мария Корецкая',    email: 'm.koreckaya@school.ru',    phone: '+7 (985) 401-89-23',
    group: 'Web-fullstack-2',          courses: ['Веб-разработка', 'React Pro', 'SQL'], status: 'active',
    progress: 91, payment: 'paid', paidUntil: '30 авг.', enrolled: '11 сен. 2025', lastActive: 'вчера', avatarSeed: 'emerald' },
  { id: 4, name: 'Иван Козлов',       email: 'kozlov.iv@list.ru',        phone: '+7 (911) 223-78-65',
    group: '3D-новички',               courses: ['Дизайн 3D-моделей'], status: 'new',
    progress: 8, payment: 'paid', paidUntil: '21 июн.', enrolled: '14 апр. 2026', lastActive: '20 мин назад', avatarSeed: 'orange' },
  { id: 5, name: 'Елена Петрова',     email: 'elena.p@mail.ru',          phone: '+7 (926) 770-12-04',
    group: 'Иллюстрация-А',           courses: ['Иллюстрация', 'Скетчинг'], status: 'active',
    progress: 64, payment: 'paid', paidUntil: '02 авг.', enrolled: '22 окт. 2025', lastActive: '3 часа назад', avatarSeed: 'violet' },
  { id: 6, name: 'Сергей Новиков',    email: 's.novikov@gmail.com',      phone: '+7 (903) 112-66-30',
    group: 'Web-fullstack-2',          courses: ['Веб-разработка'], status: 'paused',
    progress: 35, payment: 'overdue', paidUntil: '18 мар.', enrolled: '06 дек. 2025', lastActive: '12 дней назад', avatarSeed: 'rose' },
  { id: 7, name: 'Ольга Иванова',     email: 'olga.ivanova@yandex.ru',   phone: '+7 (964) 803-49-15',
    group: 'Дизайн-3 · поток апр.',   courses: ['UX/UI дизайн'], status: 'active',
    progress: 56, payment: 'paid', paidUntil: '15 июл.', enrolled: '03 фев. 2026', lastActive: '1 час назад', avatarSeed: 'teal' },
  { id: 8, name: 'Артём Захаров',     email: 'a.zaharov@gmail.com',      phone: '+7 (915) 644-21-88',
    group: 'Python-junior · б.',      courses: ['Python для детей', 'Алгоритмы'], status: 'active',
    progress: 73, payment: 'paid', paidUntil: '10 авг.', enrolled: '18 янв. 2026', lastActive: '40 мин назад', avatarSeed: 'indigo' },
  { id: 9, name: 'Виктория Лебедева', email: 'v.lebedeva@list.ru',       phone: '+7 (926) 309-55-71',
    group: 'Иллюстрация-А',           courses: ['Иллюстрация'], status: 'active',
    progress: 88, payment: 'paid', paidUntil: '25 июл.', enrolled: '22 окт. 2025', lastActive: '15 мин назад', avatarSeed: 'pink' },
  { id: 10, name: 'Никита Громов',    email: 'gromov.n@inbox.ru',        phone: '+7 (903) 887-23-44',
    group: 'Web-fullstack-2',          courses: ['Веб-разработка', 'React Pro'], status: 'active',
    progress: 47, payment: 'pending', paidUntil: '01 мая (счёт)', enrolled: '11 сен. 2025', lastActive: 'вчера', avatarSeed: 'blue' },
  { id: 11, name: 'Татьяна Орлова',   email: 't.orlova@gmail.com',       phone: '+7 (985) 211-78-09',
    group: 'Дизайн-3 · поток фев.',   courses: ['UX/UI дизайн', 'Motion-основы'], status: 'active',
    progress: 82, payment: 'paid', paidUntil: '04 сен.', enrolled: '14 ноя. 2025', lastActive: '2 часа назад', avatarSeed: 'emerald' },
  { id: 12, name: 'Кирилл Михайлов',  email: 'k.mikhaylov@gmail.com',    phone: '+7 (911) 502-13-66',
    group: '3D-новички',               courses: ['Дизайн 3D-моделей'], status: 'new',
    progress: 4, payment: 'paid', paidUntil: '21 июн.', enrolled: '16 апр. 2026', lastActive: '8 мин назад', avatarSeed: 'orange' },
  { id: 13, name: 'Алина Беляева',    email: 'a.belyaeva@school.ru',     phone: '+7 (903) 156-78-22',
    group: 'Иллюстрация-А',           courses: ['Иллюстрация', 'Скетчинг', 'Цвет в дизайне'], status: 'active',
    progress: 94, payment: 'paid', paidUntil: '10 сен.', enrolled: '22 окт. 2025', lastActive: 'только что', avatarSeed: 'violet' },
  { id: 14, name: 'Павел Ефимов',     email: 'p.efimov@yandex.ru',       phone: '+7 (915) 488-90-13',
    group: 'Python-junior · б.',      courses: ['Python для детей'], status: 'paused',
    progress: 22, payment: 'overdue', paidUntil: '12 фев.', enrolled: '06 дек. 2025', lastActive: '24 дня назад', avatarSeed: 'rose' },
];

window.STUDENTS = STUDENTS;
