// <auto-generated />
using Edvantix.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.Catalog.Domain.AggregatesModel.CountryAggregate.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("alpha3code");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ru");

                    b.Property<int>("NumericCode")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_code");

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("phone_prefix");

                    b.HasKey("Code")
                        .HasName("pk_countries");

                    b.HasIndex("Alpha3Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_alpha3code");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_countries_currency_code");

                    b.HasIndex("NameEn")
                        .HasDatabaseName("ix_countries_name_en");

                    b.HasIndex("NumericCode")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_numeric_code");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Edvantix.Catalog.Domain.AggregatesModel.CurrencyAggregate.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<int>("DecimalDigits")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_digits");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ru");

                    b.Property<int>("NumericCode")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_code");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("pk_currencies");

                    b.HasIndex("NumericCode")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_numeric_code");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("Edvantix.Catalog.Domain.AggregatesModel.LanguageAggregate.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ru");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("native_name");

                    b.HasKey("Code")
                        .HasName("pk_languages");

                    b.HasIndex("NameEn")
                        .HasDatabaseName("ix_languages_name_en");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Edvantix.Catalog.Domain.AggregatesModel.RegionAggregate.Region", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ru");

                    b.HasKey("Code")
                        .HasName("pk_regions");

                    b.HasIndex("NameEn")
                        .HasDatabaseName("ix_regions_name_en");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Edvantix.Catalog.Domain.AggregatesModel.TimezoneAggregate.Timezone", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ru");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("utc_offset_minutes");

                    b.HasKey("Code")
                        .HasName("pk_timezones");

                    b.HasIndex("NameEn")
                        .HasDatabaseName("ix_timezones_name_en");

                    b.HasIndex("UtcOffsetMinutes")
                        .HasDatabaseName("ix_timezones_utc_offset_minutes");

                    b.ToTable("timezones", (string)null);
                });

            modelBuilder.Entity("Edvantix.Catalog.Domain.AggregatesModel.CountryAggregate.Country", b =>
                {
                    b.HasOne("Edvantix.Catalog.Domain.AggregatesModel.CurrencyAggregate.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_countries_currencies_currency_code");
                });
#pragma warning restore 612, 618
        }
    }
}
