// Course detail data — модули и уроки конкретного курса.
// Курс = набор модулей. Модуль = набор уроков. Урок — атомарная единица программы.

const COURSE = {
  id: 2,
  code: 'EN-GEN-B1',
  name: 'General English · Intermediate',
  subject: 'english',
  level: 'B1',
  status: 'Active',
  cover: 'GI',
  durationWeeks: 33,
  lessons: 66,
  groups: 4,
  students: 38,
  owner: 'Анна Мельникова',
  updated: '02.05.2026',
  created: '14.08.2025',
  description:
    'Программа уровня B1 для подростков и взрослых. 6 тематических модулей плюс блок повторения: грамматика, лексика, разговорные сессии, аудирование и письмо. Каждый урок — 80 минут, 2 раза в неделю.',
  goals: [
    'Уверенно говорить на бытовые и рабочие темы',
    'Понимать живую речь носителей со средним темпом',
    'Писать письма, эссе и короткие отчёты на 200–300 слов',
    'Готовиться к переходу на B2 / IELTS 5.5',
  ],
};

// Тип урока определяет иконку, цвет акцента и формат содержимого
const LESSON_TYPES = {
  lecture:   { label: 'Теория',      icon: 'BookOpen',     fg: '#4338ca', bg: '#eef2ff' },
  practice:  { label: 'Практика',    icon: 'FileText',     fg: '#0369a1', bg: '#e0f2fe' },
  speaking:  { label: 'Разговорная', icon: 'MessageCircle',fg: '#0f766e', bg: '#ccfbf1' },
  listening: { label: 'Аудирование', icon: 'Bell',         fg: '#6d28d9', bg: '#f3e8ff' },
  writing:   { label: 'Письмо',      icon: 'Send',         fg: '#92400e', bg: '#fef3c7' },
  test:      { label: 'Контрольная', icon: 'CircleCheck',  fg: '#b91c1c', bg: '#fee2e2' },
  review:    { label: 'Повторение',  icon: 'Sparkles',     fg: '#475569', bg: '#f1f5f9' },
};

const LESSON_STATUSES = {
  published: { label: 'Опубликован', dot: '#10b981', fg: '#047857', bg: '#d1fae5' },
  draft:     { label: 'Черновик',    dot: '#f59e0b', fg: '#92400e', bg: '#fef3c7' },
  planned:   { label: 'Запланирован',dot: '#94a3b8', fg: '#475569', bg: '#f1f5f9' },
};

// Структура одного урока: blocks — это «общая инфа + что-то ещё», на чём будет
// строиться интерактивная логика (теория, видео, упражнение, тест, обсуждение).
const BLOCK_TYPES = {
  intro:    { label: 'Вступление',    icon: 'Info' },
  theory:   { label: 'Теория',         icon: 'BookOpen' },
  video:    { label: 'Видео',          icon: 'FileText' },
  exercise: { label: 'Упражнение',     icon: 'Sparkles' },
  speaking: { label: 'Разговор',       icon: 'MessageCircle' },
  listening:{ label: 'Аудио',          icon: 'Bell' },
  writing:  { label: 'Письменная',     icon: 'Send' },
  quiz:     { label: 'Мини-квиз',      icon: 'CircleCheck' },
  homework: { label: 'Домашнее',       icon: 'Briefcase' },
};

// Модули программы. lessons считается суммарно из самих уроков,
// но дублируем published/total для прогресса.
const MODULES = [
  {
    id: 'm1',
    n: 1,
    name: 'Знакомство и повседневная жизнь',
    summary: 'Present Simple/Continuous, рассказ о себе, описания людей',
    weeks: 5,
    lessons: [
      { id: 101, n: 1, title: 'Вводное занятие. Self-introduction',
        type: 'lecture', status: 'published', minutes: 80, blocks: 6, materials: 4,
        objectives: ['Снять страх говорения', 'Освоить формулу самопрезентации'],
        date: '15.09.2025' },
      { id: 102, n: 2, title: 'Present Simple vs Continuous',
        type: 'practice', status: 'published', minutes: 80, blocks: 8, materials: 5,
        objectives: ['Различать ситуативное и регулярное', 'State verbs'],
        date: '17.09.2025' },
      { id: 103, n: 3, title: 'Daily routines · vocabulary',
        type: 'speaking', status: 'published', minutes: 80, blocks: 5, materials: 3,
        objectives: ['25 коллокаций про рутину', 'Mini-talk 2 минуты'],
        date: '22.09.2025' },
      { id: 104, n: 4, title: 'Listening: Morning in London',
        type: 'listening', status: 'published', minutes: 80, blocks: 6, materials: 4,
        date: '24.09.2025' },
      { id: 105, n: 5, title: 'Describing people · adjectives',
        type: 'lecture', status: 'published', minutes: 80, blocks: 7, materials: 4,
        date: '29.09.2025' },
      { id: 106, n: 6, title: 'Writing: A letter to a pen-friend',
        type: 'writing', status: 'published', minutes: 80, blocks: 5, materials: 3,
        date: '01.10.2025' },
      { id: 107, n: 7, title: 'Speaking club · my week',
        type: 'speaking', status: 'published', minutes: 80, blocks: 4, materials: 2,
        date: '06.10.2025' },
      { id: 108, n: 8, title: 'Module 1 review & test',
        type: 'test', status: 'published', minutes: 80, blocks: 3, materials: 2,
        date: '08.10.2025' },
    ],
  },
  {
    id: 'm2',
    n: 2,
    name: 'Прошлое и истории',
    summary: 'Past Simple/Continuous/Perfect, storytelling, анекдоты',
    weeks: 6,
    lessons: [
      { id: 201, n: 9,  title: 'Past Simple: regular & irregular',
        type: 'lecture', status: 'published', minutes: 80, blocks: 7, materials: 5, date: '13.10.2025' },
      { id: 202, n: 10, title: 'Past Continuous · interrupted actions',
        type: 'practice', status: 'published', minutes: 80, blocks: 6, materials: 4, date: '15.10.2025' },
      { id: 203, n: 11, title: 'Storytelling: childhood memories',
        type: 'speaking', status: 'published', minutes: 80, blocks: 5, materials: 3, date: '20.10.2025' },
      { id: 204, n: 12, title: 'Used to / would',
        type: 'lecture', status: 'published', minutes: 80, blocks: 6, materials: 4, date: '22.10.2025' },
      { id: 205, n: 13, title: 'Listening: True crime podcast',
        type: 'listening', status: 'published', minutes: 80, blocks: 7, materials: 4, date: '27.10.2025' },
      { id: 206, n: 14, title: 'Past Perfect — sequence of events',
        type: 'lecture', status: 'published', minutes: 80, blocks: 8, materials: 5, date: '29.10.2025' },
      { id: 207, n: 15, title: 'Writing: a short story (180 слов)',
        type: 'writing', status: 'published', minutes: 80, blocks: 5, materials: 3, date: '03.11.2025' },
      { id: 208, n: 16, title: 'Speaking: tell me a funny story',
        type: 'speaking', status: 'published', minutes: 80, blocks: 4, materials: 2, date: '05.11.2025' },
      { id: 209, n: 17, title: 'Vocabulary: emotions & reactions',
        type: 'practice', status: 'published', minutes: 80, blocks: 6, materials: 4, date: '10.11.2025' },
      { id: 210, n: 18, title: 'Module 2 review & test',
        type: 'test', status: 'published', minutes: 80, blocks: 3, materials: 2, date: '12.11.2025' },
    ],
  },
  {
    id: 'm3',
    n: 3,
    name: 'Путешествия и планы',
    summary: 'Future forms, travel vocabulary, ролевые в аэропорту/отеле',
    weeks: 5,
    lessons: [
      { id: 301, n: 19, title: 'Going to / Will / Present Continuous for future',
        type: 'lecture', status: 'published', minutes: 80, blocks: 7, materials: 4, date: '17.11.2025' },
      { id: 302, n: 20, title: 'Travel vocabulary intensive',
        type: 'practice', status: 'published', minutes: 80, blocks: 6, materials: 5, date: '19.11.2025' },
      { id: 303, n: 21, title: 'Roleplay: at the airport',
        type: 'speaking', status: 'published', minutes: 80, blocks: 5, materials: 3, date: '24.11.2025' },
      { id: 304, n: 22, title: 'Listening: travel vlogs',
        type: 'listening', status: 'published', minutes: 80, blocks: 6, materials: 4, date: '26.11.2025' },
      { id: 305, n: 23, title: 'Roleplay: hotel check-in',
        type: 'speaking', status: 'published', minutes: 80, blocks: 5, materials: 3, date: '01.12.2025' },
      { id: 306, n: 24, title: 'Writing: a travel review',
        type: 'writing', status: 'draft', minutes: 80, blocks: 5, materials: 2, date: '03.12.2025' },
      { id: 307, n: 25, title: 'Speaking club · best & worst trip',
        type: 'speaking', status: 'published', minutes: 80, blocks: 4, materials: 2, date: '08.12.2025' },
      { id: 308, n: 26, title: 'Module 3 review & test',
        type: 'test', status: 'published', minutes: 80, blocks: 3, materials: 2, date: '10.12.2025' },
    ],
  },
  {
    id: 'm4',
    n: 4,
    name: 'Работа и карьера',
    summary: 'Modal verbs, CV & cover letter, job interview',
    weeks: 7,
    lessons: [
      { id: 401, n: 27, title: 'Modal verbs of obligation: must, have to, should',
        type: 'lecture', status: 'published', minutes: 80, blocks: 7, materials: 5, date: '15.12.2025' },
      { id: 402, n: 28, title: 'Job vocabulary & professions',
        type: 'practice', status: 'published', minutes: 80, blocks: 6, materials: 4, date: '17.12.2025' },
      { id: 403, n: 29, title: 'Speaking: my dream job',
        type: 'speaking', status: 'published', minutes: 80, blocks: 4, materials: 2, date: '12.01.2026' },
      { id: 404, n: 30, title: 'Listening: real interview transcripts',
        type: 'listening', status: 'published', minutes: 80, blocks: 6, materials: 4, date: '14.01.2026' },
      { id: 405, n: 31, title: 'Writing: CV in English',
        type: 'writing', status: 'published', minutes: 80, blocks: 6, materials: 5, date: '19.01.2026' },
      { id: 406, n: 32, title: 'Writing: cover letter',
        type: 'writing', status: 'published', minutes: 80, blocks: 5, materials: 4, date: '21.01.2026' },
      { id: 407, n: 33, title: 'Roleplay: job interview',
        type: 'speaking', status: 'draft', minutes: 80, blocks: 5, materials: 3, date: '26.01.2026' },
      { id: 408, n: 34, title: 'Office small talk',
        type: 'speaking', status: 'planned', minutes: 80, blocks: 4, materials: 2, date: '28.01.2026' },
      { id: 409, n: 35, title: 'Email etiquette',
        type: 'writing', status: 'planned', minutes: 80, blocks: 5, materials: 3, date: '02.02.2026' },
      { id: 410, n: 36, title: 'Vocabulary: business idioms',
        type: 'practice', status: 'planned', minutes: 80, blocks: 6, materials: 3, date: '04.02.2026' },
      { id: 411, n: 37, title: 'Mock interview · pair work',
        type: 'speaking', status: 'planned', minutes: 80, blocks: 4, materials: 2, date: '09.02.2026' },
      { id: 412, n: 38, title: 'Module 4 review & test',
        type: 'test', status: 'planned', minutes: 80, blocks: 3, materials: 2, date: '11.02.2026' },
    ],
  },
  {
    id: 'm5',
    n: 5,
    name: 'Мнения и дебаты',
    summary: 'Conditionals 0–II, агрить и контрить, дискуссии',
    weeks: 5,
    lessons: [
      { id: 501, n: 39, title: 'Zero & First Conditional',
        type: 'lecture', status: 'planned', minutes: 80, blocks: 7, materials: 4, date: '16.02.2026' },
      { id: 502, n: 40, title: 'Second Conditional',
        type: 'lecture', status: 'planned', minutes: 80, blocks: 7, materials: 4, date: '18.02.2026' },
      { id: 503, n: 41, title: 'Expressing opinion: phrases',
        type: 'practice', status: 'planned', minutes: 80, blocks: 6, materials: 3, date: '23.02.2026' },
      { id: 504, n: 42, title: 'Agreeing & disagreeing politely',
        type: 'speaking', status: 'planned', minutes: 80, blocks: 5, materials: 3, date: '25.02.2026' },
      { id: 505, n: 43, title: 'Listening: TED-style talks',
        type: 'listening', status: 'planned', minutes: 80, blocks: 6, materials: 4, date: '02.03.2026' },
      { id: 506, n: 44, title: 'Debate: technology in classrooms',
        type: 'speaking', status: 'planned', minutes: 80, blocks: 4, materials: 2, date: '04.03.2026' },
      { id: 507, n: 45, title: 'Writing: opinion essay',
        type: 'writing', status: 'planned', minutes: 80, blocks: 6, materials: 4, date: '09.03.2026' },
      { id: 508, n: 46, title: 'Speaking club · debate finale',
        type: 'speaking', status: 'planned', minutes: 80, blocks: 4, materials: 2, date: '11.03.2026' },
      { id: 509, n: 47, title: 'Vocabulary: connectors & signposts',
        type: 'practice', status: 'planned', minutes: 80, blocks: 6, materials: 3, date: '16.03.2026' },
      { id: 510, n: 48, title: 'Module 5 review & test',
        type: 'test', status: 'planned', minutes: 80, blocks: 3, materials: 2, date: '18.03.2026' },
    ],
  },
  {
    id: 'm6',
    n: 6,
    name: 'Будущее и гипотезы',
    summary: 'Третий кондишнал, wish/regret, технологии будущего',
    weeks: 5,
    lessons: Array.from({length: 12}, (_, i) => ({
      id: 600 + i + 1,
      n: 49 + i,
      title: ['Future Continuous & Perfect',
              'Third Conditional',
              'I wish / If only',
              'Vocabulary: science & tech',
              'Listening: futurists podcast',
              'Speaking: predictions for 2050',
              'Reading: short sci-fi',
              'Writing: a prediction essay',
              'Roleplay: dilemma debate',
              'Speaking club · regrets',
              'Mixed practice: all conditionals',
              'Module 6 review & test'][i],
      type: ['lecture','lecture','lecture','practice','listening','speaking','practice','writing','speaking','speaking','practice','test'][i],
      status: 'planned', minutes: 80,
      blocks: [7,7,6,6,6,4,5,6,5,4,6,3][i],
      materials: [4,4,3,4,4,2,3,4,3,2,3,2][i],
      date: ['23.03.2026','25.03.2026','30.03.2026','01.04.2026','06.04.2026','08.04.2026',
             '13.04.2026','15.04.2026','20.04.2026','22.04.2026','27.04.2026','29.04.2026'][i],
    })),
  },
  {
    id: 'm7',
    n: 7,
    name: 'Финальное повторение',
    summary: 'Сводное повторение, mock-test, защита проектов',
    weeks: 3,
    lessons: Array.from({length: 6}, (_, i) => ({
      id: 700 + i + 1,
      n: 61 + i,
      title: ['Grammar marathon · part 1',
              'Grammar marathon · part 2',
              'Vocabulary marathon',
              'Mock final test',
              'Project presentations · group A',
              'Project presentations · group B'][i],
      type: ['review','review','review','test','speaking','speaking'][i],
      status: 'planned', minutes: 80,
      blocks: [8,8,7,3,4,4][i],
      materials: [5,5,4,2,2,2][i],
      date: ['04.05.2026','06.05.2026','11.05.2026','13.05.2026','18.05.2026','20.05.2026'][i],
    })),
  },
];

// Группы, использующие этот курс — для бокового списка
const COURSE_GROUPS = [
  { id: 1, name: 'B1-Утро · вт/чт 10:00', students: 11, progress: 0.62, next: 'Урок 23 · 11.05' },
  { id: 2, name: 'B1-Вечер · пн/ср 19:00', students: 9,  progress: 0.58, next: 'Урок 22 · 11.05' },
  { id: 3, name: 'B1-Сб · 12:00',         students: 8,  progress: 0.71, next: 'Урок 25 · 09.05' },
  { id: 4, name: 'B1-Корп · Альфа',       students: 10, progress: 0.45, next: 'Урок 18 · 12.05' },
];

window.COURSE = COURSE;
window.MODULES = MODULES;
window.LESSON_TYPES = LESSON_TYPES;
window.LESSON_STATUSES = LESSON_STATUSES;
window.BLOCK_TYPES = BLOCK_TYPES;
window.COURSE_GROUPS = COURSE_GROUPS;
