using Edvantix.Chassis.EF.Configurations;
using Edvantix.Organizations.Domain.AggregatesModel.OrganizationAggregate;

namespace Edvantix.Organizations.Infrastructure.EntityConfigurations;

/// <summary>
/// EF Core configuration for <see cref="Organization"/>.
/// Maps to the <c>organizations</c> table. No HasQueryFilter needed — Organization IS the
/// tenant root and is not scoped to another tenant.
/// ValueGeneratedNever is set because Organization IDs are provided externally
/// (e.g., from Keycloak realm ID or provisioning system), not auto-generated by the DB.
/// </summary>
internal sealed class OrganizationConfiguration : IEntityTypeConfiguration<Organization>
{
    public void Configure(EntityTypeBuilder<Organization> builder)
    {
        builder.ToTable("organizations");
        builder.HasKey(o => o.Id);
        builder.Property(o => o.Id).ValueGeneratedNever();
    }
}
