// <auto-generated />
using Edvantix.EntityHub.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.EntityHub.Infrastructure.Migrations
{
    [DbContext(typeof(EntityHubContext))]
    [Migration("20251211192257_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.EntityTypeAggregate.EntityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description")
                        .HasComment("Описание сущности");

                    b.Property<long>("MicroserviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_id")
                        .HasComment("Идентификатор микросервиса");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("Наименование сущности");

                    b.HasKey("Id")
                        .HasName("pk_entity_type");

                    b.HasIndex("MicroserviceId")
                        .HasDatabaseName("ix_entity_type_microservice_id");

                    b.ToTable("entity_type", (string)null);
                });

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.MicroserviceAggregate.Microservice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Наименование сервиса");

                    b.HasKey("Id")
                        .HasName("pk_microservice");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_microservice_name");

                    b.ToTable("microservice", (string)null);
                });

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.EntityTypeAggregate.EntityType", b =>
                {
                    b.HasOne("Edvantix.EntityHub.Domain.AggregatesModel.MicroserviceAggregate.Microservice", "Microservice")
                        .WithMany()
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_type_microservice_microservice_id");

                    b.Navigation("Microservice");
                });
#pragma warning restore 612, 618
        }
    }
}
