// <auto-generated />
using Edvantix.EntityHub.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.EntityHub.Infrastructure.Migrations
{
    [DbContext(typeof(EntityHubContext))]
    partial class EntityHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.EntityGroupAggregate.EntityGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("Наименование группы сущностей");

                    b.HasKey("Id")
                        .HasName("pk_entity_group");

                    b.ToTable("entity_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "System"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Hidden"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Reference"
                        });
                });

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.EntityTypeAggregate.EntityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description")
                        .HasComment("Описание сущности");

                    b.Property<long>("EntityGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(2L)
                        .HasColumnName("entity_group_id")
                        .HasComment("Идентификатор группы сущности");

                    b.Property<long>("MicroserviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_id")
                        .HasComment("Идентификатор микросервиса");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("Наименование сущности");

                    b.HasKey("Id")
                        .HasName("pk_entity_type");

                    b.HasIndex("EntityGroupId")
                        .HasDatabaseName("ix_entity_type_entity_group_id");

                    b.HasIndex("MicroserviceId")
                        .HasDatabaseName("ix_entity_type_microservice_id");

                    b.ToTable("entity_type", (string)null);
                });

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.MicroserviceAggregate.Microservice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Наименование сервиса");

                    b.HasKey("Id")
                        .HasName("pk_microservice");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_microservice_name");

                    b.ToTable("microservice", (string)null);
                });

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.EntityTypeAggregate.EntityType", b =>
                {
                    b.HasOne("Edvantix.EntityHub.Domain.AggregatesModel.EntityGroupAggregate.EntityGroup", "EntityGroup")
                        .WithMany("Entities")
                        .HasForeignKey("EntityGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_type_entity_group_entity_group_id");

                    b.HasOne("Edvantix.EntityHub.Domain.AggregatesModel.MicroserviceAggregate.Microservice", "Microservice")
                        .WithMany()
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_type_microservice_microservice_id");

                    b.Navigation("EntityGroup");

                    b.Navigation("Microservice");
                });

            modelBuilder.Entity("Edvantix.EntityHub.Domain.AggregatesModel.EntityGroupAggregate.EntityGroup", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
