// <auto-generated />
using System;
using Edvantix.Schedule.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.Schedule.Infrastructure.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20260512172641_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.GroupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<int?>("BiweeklyParity")
                        .HasColumnType("integer")
                        .HasColumnName("biweekly_parity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EndMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("end_mode");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<short?>("LessonCount")
                        .HasColumnType("smallint")
                        .HasColumnName("lesson_count");

                    b.Property<short>("LessonDurationMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("lesson_duration_minutes");

                    b.Property<bool>("NotifyStudents")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_students");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence");

                    b.Property<bool>("SkipHolidays")
                        .HasColumnType("boolean")
                        .HasColumnName("skip_holidays");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_group_schedules");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_schedules_group_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_group_schedules_organization_id");

                    b.ToTable("group_schedules", (string)null);
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.ScheduleException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_exceptions");

                    b.HasIndex("ScheduleId", "ExceptionDate")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_exceptions_schedule_id_exception_date");

                    b.ToTable("schedule_exceptions", (string)null);
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.ScheduleSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("start_minutes");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer")
                        .HasColumnName("weekday");

                    b.HasKey("Id")
                        .HasName("pk_schedule_slots");

                    b.HasIndex("ScheduleId", "Weekday", "StartMinutes")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_slots_schedule_id_weekday_start_minutes");

                    b.ToTable("schedule_slots", (string)null);
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.HolidayAggregate.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsRecurringAnnually")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring_annually");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_holidays");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_holidays_country_code");

                    b.HasIndex("CountryCode", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_holidays_country_code_date");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.LessonOccurrenceAggregate.LessonOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateOnly>("LessonDate")
                        .HasColumnType("date")
                        .HasColumnName("lesson_date");

                    b.Property<Guid?>("LessonRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_ref_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skip_reason");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("start_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_lesson_occurrences");

                    b.HasIndex("GroupId", "LessonDate")
                        .HasDatabaseName("ix_lesson_occurrences_group_id_lesson_date");

                    b.HasIndex("ScheduleId", "Status")
                        .HasDatabaseName("ix_lesson_occurrences_schedule_id_status");

                    b.ToTable("lesson_occurrences", (string)null);
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.ScheduleException", b =>
                {
                    b.HasOne("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.GroupSchedule", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_exceptions_group_schedules_schedule_id");
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.ScheduleSlot", b =>
                {
                    b.HasOne("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.GroupSchedule", null)
                        .WithMany("Slots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_slots_group_schedules_schedule_id");
                });

            modelBuilder.Entity("Edvantix.Schedule.Domain.AggregatesModel.GroupScheduleAggregate.GroupSchedule", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
