// <auto-generated />
using System;
using Edvantix.ProfileService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.ProfileService.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20260117223010_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.ContactAggregate.UserContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_contact");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_user_contact_profile_id");

                    b.HasIndex("ProfileId", "Type", "Value")
                        .HasDatabaseName("ix_user_contact_profile_id_type_value");

                    b.ToTable("user_contact", (string)null);
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.EducationAggregate.Education", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<long>("EducationLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("education_level_id");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.HasKey("Id")
                        .HasName("pk_education");

                    b.HasIndex("EducationLevelId")
                        .HasDatabaseName("ix_education_education_level_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_education_is_deleted");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_education_profile_id");

                    b.ToTable("education", (string)null);
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.EducationAggregate.EducationLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_education_level");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_education_level_code");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_education_level_is_deleted");

                    b.ToTable("education_level", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "preschool",
                            IsDeleted = false,
                            Name = "Дошкольное образование"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "general_secondary",
                            IsDeleted = false,
                            Name = "Общее среднее образование"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "vocational_technical",
                            IsDeleted = false,
                            Name = "Профессионально-техническое образование"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "secondary_specialized",
                            IsDeleted = false,
                            Name = "Среднее специальное образование"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "higher_bachelor",
                            IsDeleted = false,
                            Name = "Высшее образование (I ступень)"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "higher_master",
                            IsDeleted = false,
                            Name = "Высшее образование (II ступень)"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "postgraduate",
                            IsDeleted = false,
                            Name = "Послевузовское образование"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "additional_children",
                            IsDeleted = false,
                            Name = "Дополнительное образование детей и молодежи"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "additional_adults",
                            IsDeleted = false,
                            Name = "Дополнительное образование взрослых"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "special",
                            IsDeleted = false,
                            Name = "Специальное образование"
                        });
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.EmploymentHistoryAggregate.EmploymentHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("position");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workplace");

                    b.HasKey("Id")
                        .HasName("pk_employment_history");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_employment_history_profile_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_employment_history_start_date");

                    b.ToTable("employment_history", (string)null);
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.FullNameAggregate.FullName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_full_name");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_full_name_profile_id");

                    b.ToTable("full_name", (string)null);
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.ProfileAggregate.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_account_id");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.ContactAggregate.UserContact", b =>
                {
                    b.HasOne("Edvantix.ProfileService.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany("Contacts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_contact_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.EducationAggregate.Education", b =>
                {
                    b.HasOne("Edvantix.ProfileService.Domain.AggregatesModel.EducationAggregate.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_education_education_level_education_level_id");

                    b.HasOne("Edvantix.ProfileService.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany("Educations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_education_profile_profile_id");

                    b.Navigation("EducationLevel");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.EmploymentHistoryAggregate.EmploymentHistory", b =>
                {
                    b.HasOne("Edvantix.ProfileService.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany("EmploymentHistories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employment_history_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.FullNameAggregate.FullName", b =>
                {
                    b.HasOne("Edvantix.ProfileService.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithOne("FullName")
                        .HasForeignKey("Edvantix.ProfileService.Domain.AggregatesModel.FullNameAggregate.FullName", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_full_name_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.ProfileService.Domain.AggregatesModel.ProfileAggregate.Profile", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Educations");

                    b.Navigation("EmploymentHistories");

                    b.Navigation("FullName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
