// <auto-generated />
using System;
using Edvantix.OrganizationManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.OrganizationManagement.Migrations
{
    [DbContext(typeof(OrganizationContext))]
    [Migration("20251217213720_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.ContactAggregate.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_contact_organization_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_contact_type");

                    b.HasIndex("OrganizationId", "Type")
                        .HasDatabaseName("ix_contact_organization_id_type");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.MemberAggregate.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_member");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_member_is_deleted");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_member_organization_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_member_person_id");

                    b.HasIndex("OrganizationId", "PersonId", "IsDeleted")
                        .HasDatabaseName("ix_member_organization_id_person_id_is_deleted");

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.OrganizationAggregate.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_latin");

                    b.Property<string>("PrintName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("print_name");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organization_name");

                    b.HasIndex("NameLatin")
                        .HasDatabaseName("ix_organization_name_latin");

                    b.HasIndex("RegistrationDate")
                        .HasDatabaseName("ix_organization_registration_date");

                    b.HasIndex("ShortName")
                        .HasDatabaseName("ix_organization_short_name");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_subscription");

                    b.HasIndex("DateEnd")
                        .HasDatabaseName("ix_subscription_date_end");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_subscription_organization_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_subscription_id");

                    b.HasIndex("OrganizationId", "DateStart", "DateEnd")
                        .HasDatabaseName("ix_subscription_organization_id_date_start_date_end");

                    b.ToTable("subscription", (string)null);
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.UsageAggregate.Usage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LimitId")
                        .HasColumnType("bigint")
                        .HasColumnName("limit_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_usage");

                    b.HasIndex("LimitId")
                        .HasDatabaseName("ix_usage_limit_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_usage_organization_id");

                    b.HasIndex("OrganizationId", "LimitId")
                        .HasDatabaseName("ix_usage_organization_id_limit_id");

                    b.ToTable("usage", (string)null);
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.ContactAggregate.Contact", b =>
                {
                    b.HasOne("Edvantix.OrganizationManagement.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_organization_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.MemberAggregate.Member", b =>
                {
                    b.HasOne("Edvantix.OrganizationManagement.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_organization_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.SubscriptionAggregate.Subscription", b =>
                {
                    b.HasOne("Edvantix.OrganizationManagement.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany("Subscriptions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_organization_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.UsageAggregate.Usage", b =>
                {
                    b.HasOne("Edvantix.OrganizationManagement.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usage_organization_organization_id");

                    b.HasOne("Edvantix.OrganizationManagement.Domain.AggregatesModel.SubscriptionAggregate.Subscription", null)
                        .WithMany("Usages")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usage_subscription_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.OrganizationAggregate.Organization", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Members");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Edvantix.OrganizationManagement.Domain.AggregatesModel.SubscriptionAggregate.Subscription", b =>
                {
                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
