// <auto-generated />
using System;
using Edvantix.Company.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.Company.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationContext))]
    [Migration("20260214101427_Rework Scheme")]
    partial class ReworkScheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.ContactAggregate.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_contact_organization_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_contact_type");

                    b.HasIndex("OrganizationId", "Type")
                        .HasDatabaseName("ix_contact_organization_id_type");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.GroupAggregate.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_group_name");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_group_organization_id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.GroupAggregate.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_group_member");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_member_group_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_group_member_profile_id");

                    b.HasIndex("GroupId", "ProfileId", "IsDeleted")
                        .HasDatabaseName("ix_group_member_group_id_profile_id_is_deleted");

                    b.ToTable("group_member", (string)null);
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.OrganizationAggregate.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_latin");

                    b.Property<string>("PrintName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("print_name");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organization_name");

                    b.HasIndex("NameLatin")
                        .HasDatabaseName("ix_organization_name_latin");

                    b.HasIndex("RegistrationDate")
                        .HasDatabaseName("ix_organization_registration_date");

                    b.HasIndex("ShortName")
                        .HasDatabaseName("ix_organization_short_name");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.OrganizationMemberAggregate.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_organization_member");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_member_organization_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_organization_member_profile_id");

                    b.HasIndex("OrganizationId", "ProfileId", "IsDeleted")
                        .HasDatabaseName("ix_organization_member_organization_id_profile_id_is_deleted");

                    b.ToTable("organization_member", (string)null);
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.ContactAggregate.Contact", b =>
                {
                    b.HasOne("Edvantix.Company.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_organization_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.GroupAggregate.Group", b =>
                {
                    b.HasOne("Edvantix.Company.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany("Groups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_organization_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.GroupAggregate.GroupMember", b =>
                {
                    b.HasOne("Edvantix.Company.Domain.AggregatesModel.GroupAggregate.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_member_group_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.OrganizationMemberAggregate.OrganizationMember", b =>
                {
                    b.HasOne("Edvantix.Company.Domain.AggregatesModel.OrganizationAggregate.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_member_organization_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.GroupAggregate.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Edvantix.Company.Domain.AggregatesModel.OrganizationAggregate.Organization", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Groups");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
