// <auto-generated />
using System;
using Edvantix.Person.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.Person.Infrastructure.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.ContactAggregate.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<long>("PersonInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_info_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("PersonInfoId")
                        .HasDatabaseName("ix_contact_person_info_id");

                    b.HasIndex("PersonInfoId", "Type", "Value")
                        .HasDatabaseName("ix_contact_person_info_id_type_value");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.EmploymentHistoryAggregate.EmploymentHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<long>("PersonInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_info_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("position");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_employment_history");

                    b.HasIndex("PersonInfoId")
                        .HasDatabaseName("ix_employment_history_person_info_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_employment_history_start_date");

                    b.ToTable("employment_history", (string)null);
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.FullNameAggregate.FullName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<long>("PersonInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_info_id");

                    b.HasKey("Id")
                        .HasName("pk_full_name");

                    b.HasIndex("PersonInfoId")
                        .IsUnique()
                        .HasDatabaseName("ix_full_name_person_info_id");

                    b.ToTable("full_name", (string)null);
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.PersonInfoAggregate.PersonInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.HasKey("Id")
                        .HasName("pk_person_info");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_info_account_id");

                    b.ToTable("person_info", (string)null);
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.ContactAggregate.Contact", b =>
                {
                    b.HasOne("Edvantix.Person.Domain.AggregatesModel.PersonInfoAggregate.PersonInfo", "PersonInfo")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_person_info_person_info_id");

                    b.Navigation("PersonInfo");
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.EmploymentHistoryAggregate.EmploymentHistory", b =>
                {
                    b.HasOne("Edvantix.Person.Domain.AggregatesModel.PersonInfoAggregate.PersonInfo", "PersonInfo")
                        .WithMany("EmploymentHistories")
                        .HasForeignKey("PersonInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employment_history_person_info_person_info_id");

                    b.Navigation("PersonInfo");
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.FullNameAggregate.FullName", b =>
                {
                    b.HasOne("Edvantix.Person.Domain.AggregatesModel.PersonInfoAggregate.PersonInfo", "PersonInfo")
                        .WithOne("FullName")
                        .HasForeignKey("Edvantix.Person.Domain.AggregatesModel.FullNameAggregate.FullName", "PersonInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_full_name_person_info_person_info_id");

                    b.Navigation("PersonInfo");
                });

            modelBuilder.Entity("Edvantix.Person.Domain.AggregatesModel.PersonInfoAggregate.PersonInfo", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("EmploymentHistories");

                    b.Navigation("FullName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
