// <auto-generated />
using System;
using Edvantix.Persona.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.Persona.Infrastructure.Migrations
{
    [DbContext(typeof(PersonaDbContext))]
    partial class PersonaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Education", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateOnly?>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("date_end");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("date_start");

                    b.Property<byte>("EducationLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("education_level");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("ProfileId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("profile_id");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.HasKey("Id")
                        .HasName("pk_education");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_education_is_deleted");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_education_profile_id");

                    b.ToTable("education", (string)null);
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.EmploymentHistory", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("position");

                    b.Property<decimal>("ProfileId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workplace");

                    b.HasKey("Id")
                        .HasName("pk_employment_history");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_employment_history_profile_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_employment_history_start_date");

                    b.ToTable("employment_history", (string)null);
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.FullName", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<decimal>("ProfileId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_full_name");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_full_name_profile_id");

                    b.ToTable("full_name", (string)null);
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Profile", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("login");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_account_id");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.ProfileContact", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("ProfileId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("profile_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_profile_contact");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_profile_contact_profile_id");

                    b.HasIndex("ProfileId", "Type", "Value")
                        .HasDatabaseName("ix_profile_contact_profile_id_type_value");

                    b.ToTable("profile_contact", (string)null);
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Education", b =>
                {
                    b.HasOne("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany("Educations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_education_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.EmploymentHistory", b =>
                {
                    b.HasOne("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany("EmploymentHistories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employment_history_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.FullName", b =>
                {
                    b.HasOne("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithOne("FullName")
                        .HasForeignKey("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.FullName", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_full_name_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.ProfileContact", b =>
                {
                    b.HasOne("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany("Contacts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_contact_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Edvantix.Persona.Domain.AggregatesModel.ProfileAggregate.Profile", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Educations");

                    b.Navigation("EmploymentHistories");

                    b.Navigation("FullName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
