// <auto-generated />
using System;
using Edvantix.Organizational.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edvantix.Organizational.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationalDbContext))]
    [Migration("20260310120000_AddOrganizationCustomRoles")]
    partial class AddOrganizationCustomRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.GroupAggregate.Group",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id").HasName("pk_group");

                    b.HasIndex("Name").HasDatabaseName("ix_group_name");

                    b.HasIndex("OrganizationId").HasDatabaseName("ix_group_organization_id");

                    b.ToTable("group", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.GroupAggregate.GroupMember",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id").HasName("pk_group_member");

                    b.HasIndex("GroupId").HasDatabaseName("ix_group_member_group_id");

                    b.HasIndex("ProfileId").HasDatabaseName("ix_group_member_profile_id");

                    b.HasIndex("GroupId", "ProfileId", "IsDeleted")
                        .HasDatabaseName("ix_group_member_group_id_profile_id_is_deleted");

                    b.ToTable("group_member", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.InvitationAggregate.Invitation",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_profile_id");

                    b.Property<string>("InviteeEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invitee_email");

                    b.Property<Guid?>("InviteeProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitee_profile_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id").HasName("pk_invitation");

                    b.HasIndex("Token").IsUnique().HasDatabaseName("ix_invitation_token");

                    b.HasIndex("InviteeProfileId", "Status")
                        .HasDatabaseName("ix_invitation_invitee_profile_id_status");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_invitation_organization_id_status");

                    b.HasIndex("OrganizationId", "InviteeEmail", "Status")
                        .HasDatabaseName("ix_invitation_organization_id_invitee_email_status");

                    b.ToTable("invitation", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.LegalFormAggregate.LegalForm",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_name");

                    b.HasKey("Id").HasName("pk_legal_form");

                    b.HasIndex("ShortName")
                        .IsUnique()
                        .HasDatabaseName("ix_legal_form_short_name");

                    b.ToTable("legal_form", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LegalFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_form_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_latin");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("integer")
                        .HasColumnName("organization_type");

                    b.Property<string>("PrintName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("print_name");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.HasKey("Id").HasName("pk_organization");

                    b.HasIndex("LegalFormId").HasDatabaseName("ix_organization_legal_form_id");

                    b.HasIndex("Name").HasDatabaseName("ix_organization_name");

                    b.HasIndex("NameLatin").HasDatabaseName("ix_organization_name_latin");

                    b.HasIndex("RegistrationDate")
                        .HasDatabaseName("ix_organization_registration_date");

                    b.HasIndex("ShortName").HasDatabaseName("ix_organization_short_name");

                    b.ToTable("organization", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.OrganizationContact",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id").HasName("pk_organization_contact");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_contact_organization_id");

                    b.HasIndex("Type").HasDatabaseName("ix_organization_contact_type");

                    b.HasIndex("OrganizationId", "Type")
                        .HasDatabaseName("ix_organization_contact_organization_id_type");

                    b.ToTable("organization_contact", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationCustomRoleAggregate.OrganizationCustomRole",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<short>("BaseRole")
                        .HasColumnType("smallint")
                        .HasColumnName("base_role");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id").HasName("pk_organization_custom_role");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_custom_role_organization_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_custom_role_organization_id_code")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("organization_custom_role", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationMemberAggregate.OrganizationMember",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленной записи");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id").HasName("pk_organization_member");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_member_organization_id");

                    b.HasIndex("ProfileId").HasDatabaseName("ix_organization_member_profile_id");

                    b.HasIndex("OrganizationId", "ProfileId", "IsDeleted")
                        .HasDatabaseName(
                            "ix_organization_member_organization_id_profile_id_is_deleted"
                        );

                    b.ToTable("organization_member", (string)null);
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.GroupAggregate.Group",
                b =>
                {
                    b.HasOne(
                            "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                            "Organization"
                        )
                        .WithMany("Groups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_organization_organization_id");

                    b.Navigation("Organization");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.GroupAggregate.GroupMember",
                b =>
                {
                    b.HasOne(
                            "Edvantix.Organizational.Domain.AggregatesModel.GroupAggregate.Group",
                            "Group"
                        )
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_member_group_group_id");

                    b.Navigation("Group");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                b =>
                {
                    b.HasOne(
                            "Edvantix.Organizational.Domain.AggregatesModel.LegalFormAggregate.LegalForm",
                            "LegalForm"
                        )
                        .WithMany()
                        .HasForeignKey("LegalFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_legal_form_legal_form_id");

                    b.Navigation("LegalForm");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.OrganizationContact",
                b =>
                {
                    b.HasOne(
                            "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                            "Organization"
                        )
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName(
                            "fk_organization_contact_organization_organization_id"
                        );

                    b.Navigation("Organization");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationCustomRoleAggregate.OrganizationCustomRole",
                b =>
                {
                    b.HasOne(
                            "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                            "Organization"
                        )
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName(
                            "fk_organization_custom_role_organization_organization_id"
                        );

                    b.Navigation("Organization");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationMemberAggregate.OrganizationMember",
                b =>
                {
                    b.HasOne(
                            "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                            "Organization"
                        )
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_member_organization_organization_id");

                    b.Navigation("Organization");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.GroupAggregate.Group",
                b =>
                {
                    b.Navigation("Members");
                }
            );

            modelBuilder.Entity(
                "Edvantix.Organizational.Domain.AggregatesModel.OrganizationAggregate.Organization",
                b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Groups");

                    b.Navigation("Members");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
